### ISSUE TITLE
Are you sure about GPL license?

### ISSUE THREAD

**Issue by XVilka** [HardwareIR/hardwareIr#1]
Ideally, it would be awesome not to restrict the usage of the library in any way.
Maybe BSD or MIT?

**Comment by Nic30** [comment]
ok changing

**Comment by Nic30** [comment]
What is the advantage for patent clause with Apace license?

**Comment by seldridge** [comment]
IANAL: It means that the author/contributor is giving the end user a license to use any patents that they own or may acquire which cover the code/contribution.

If the user initiates patent litigation against the author/contributor alleging patent infringement by the code, then they lose any patent licenses granted by the code license (i.e., derived works covered by patents can't sue upstream for infringment without invalidating the license.)

https://opensource.stackexchange.com/q/1881
